"""Deterministic API-contract change detector (feature 005, slice 4).

Pure, path-and-metadata-driven detection of API-contract evidence: OpenAPI /
Swagger specs, GraphQL schemas, protobuf/RPC, public route signatures,
request/response models, and status/error semantics. Like the schema detector it
reads only normalized changed-file metadata and the diff *handle* — never raw diff
text (FM-18, NFR-3).

Internal implementation-only handlers are deliberately *not* recognized so an
internal refactor does not masquerade as a public-contract change (US-2). Generated
specs and dynamic framework routing attach explicit uncertainty so certainty is not
inflated (FM-06, FM-07, FM-19).
"""

from __future__ import annotations

from dataclasses import dataclass

from living_adr.core.structural_change import (
    ADRRecommendation,
    ChangeOperation,
    ChangeType,
    EvidenceKind,
    ObservedOperation,
    ReasonCode,
)
from living_adr.workflow.classifiers.confidence import ConfidencePolicy
from living_adr.workflow.classifiers.inputs import (
    ChangedFileEvidence,
    ClassifierInput,
    Detection,
    DetectorOutcome,
    UncertaintyReason,
    make_evidence,
    make_no_adr,
    make_structural_change,
)

PARSER_NAME = "living-adr-api-contract-evidence"
PARSER_VERSION = "1.0.0"


@dataclass(frozen=True)
class _Subtype:
    evidence_kind: EvidenceKind
    reason_code: str
    base_confidence: float


_OPENAPI = _Subtype(
    EvidenceKind.API_OPENAPI, ReasonCode.API_OPENAPI_CONTRACT.value, 0.85
)
_GRAPHQL = _Subtype(
    EvidenceKind.API_GRAPHQL, ReasonCode.API_GRAPHQL_CONTRACT.value, 0.85
)
_PROTOBUF = _Subtype(
    EvidenceKind.API_PROTOBUF, ReasonCode.API_PROTOBUF_CONTRACT.value, 0.85
)
_ROUTE = _Subtype(EvidenceKind.API_ROUTE, ReasonCode.API_ROUTE_SIGNATURE.value, 0.74)
_MODEL = _Subtype(
    EvidenceKind.API_MODEL, ReasonCode.API_REQUEST_RESPONSE_MODEL.value, 0.74
)
_STATUS = _Subtype(EvidenceKind.API_MODEL, ReasonCode.API_STATUS_ERROR.value, 0.72)

_ROUTE_NAMES = {"routes.py", "urls.py", "router.py"}
_MODEL_NAMES = {"serializers.py", "dto.py", "schemas.py"}
_STATUS_NAMES = {"errors.py", "status.py", "status_codes.py"}


def _basename(path: str) -> str:
    return path.rsplit("/", 1)[-1]


def _has_api_context(lower: str) -> bool:
    segments = set(lower.split("/"))
    return (
        "/api/" in lower
        or "api" in segments
        or "routes" in lower
        or "controller" in lower
        or "serializer" in lower
    )


def _recognize(path: str) -> _Subtype | None:
    """Recognize a normalized path as an API-contract subtype, or ``None``."""

    lower = path.lower()
    name = _basename(lower)
    # Internal/private implementation handlers are not public contracts.
    if "/internal/" in lower or "/private/" in lower:
        return None
    if "openapi" in name or "swagger" in name:
        return _OPENAPI
    if lower.endswith((".graphql", ".gql")):
        return _GRAPHQL
    if lower.endswith(".proto"):
        return _PROTOBUF
    if not _has_api_context(lower):
        return None
    if name in _STATUS_NAMES:
        return _STATUS
    if name in _MODEL_NAMES or "serializer" in name:
        return _MODEL
    if name in _ROUTE_NAMES or "route" in name or "controller" in name:
        return _ROUTE
    return None


def _uncertainty(path: str) -> tuple[UncertaintyReason, ...]:
    lower = path.lower()
    reasons: list[UncertaintyReason] = []
    if "generated" in lower or "autogenerated" in lower:
        reasons.append(UncertaintyReason.GENERATED_ARTIFACT)
    if "dynamic" in lower:
        reasons.append(UncertaintyReason.DYNAMIC_ROUTING)
    return tuple(reasons)


def _uncertain_reason_code(
    uncertainty: tuple[UncertaintyReason, ...],
) -> str | None:
    if UncertaintyReason.DYNAMIC_ROUTING in uncertainty:
        return ReasonCode.API_DYNAMIC_ROUTE_UNCERTAIN.value
    if UncertaintyReason.GENERATED_ARTIFACT in uncertainty:
        return ReasonCode.API_GENERATED_UNCERTAIN.value
    return None


def _operation(file: ChangedFileEvidence) -> tuple[ChangeOperation, ObservedOperation]:
    status = file.status.lower()
    if status == "added":
        return ChangeOperation.ADDED, ObservedOperation.ADDED
    if status in ("removed", "deleted"):
        return ChangeOperation.REMOVED, ObservedOperation.REMOVED
    return ChangeOperation.MODIFIED, ObservedOperation.MODIFIED


def _detection(file: ChangedFileEvidence, subtype: _Subtype) -> Detection:
    operation, observed = _operation(file)
    subject = _basename(file.path).rsplit(".", 1)[0]
    comment_only = file.additions == 0 and file.deletions == 0

    if comment_only:
        return Detection(
            change_type=ChangeType.API_CONTRACT,
            subject=subject,
            source_path=file.path,
            evidence_kind=subtype.evidence_kind,
            reason_code=subtype.reason_code,
            operation=operation,
            observed_operation=observed,
            base_confidence=0.30,
            parser=PARSER_NAME,
            parser_version=PARSER_VERSION,
            forced_no_adr=True,
            no_adr_reason=ReasonCode.NO_PERSISTED_SHAPE_CHANGE.value,
        )

    uncertainty = _uncertainty(file.path)
    return Detection(
        change_type=ChangeType.API_CONTRACT,
        subject=subject,
        source_path=file.path,
        evidence_kind=subtype.evidence_kind,
        reason_code=subtype.reason_code,
        operation=operation,
        observed_operation=observed,
        base_confidence=subtype.base_confidence,
        parser=PARSER_NAME,
        parser_version=PARSER_VERSION,
        uncertainty=uncertainty,
        uncertain_reason_code=_uncertain_reason_code(uncertainty),
    )


class APIContractChangeDetector:
    """Pure API-contract evidence detector. The second feature 005 trigger class."""

    def __init__(self, policy: ConfidencePolicy | None = None) -> None:
        self.policy = policy or ConfidencePolicy()

    def detect(self, inp: ClassifierInput) -> DetectorOutcome:
        changes = []
        no_adr = []
        evidence = []
        for file in inp.changed_files:
            subtype = _recognize(file.path)
            if subtype is None:
                continue
            detection = _detection(file, subtype)
            assessment = self.policy.assess(detection, inp.repository.key)
            record_evidence = make_evidence(inp, detection, assessment)
            evidence.append(record_evidence)
            if assessment.recommendation is ADRRecommendation.DRAFT:
                changes.append(
                    make_structural_change(
                        inp, detection, record_evidence.id, assessment
                    )
                )
            else:
                no_adr.append(
                    make_no_adr(inp, detection, record_evidence.id, assessment)
                )

        changes.sort(key=lambda c: c.id)
        no_adr.sort(key=lambda o: (o.reason_code, o.id))
        evidence.sort(key=lambda e: e.id)
        return DetectorOutcome(
            changes=tuple(changes),
            no_adr_outcomes=tuple(no_adr),
            evidence=tuple(evidence),
        )


__all__ = ["APIContractChangeDetector", "PARSER_NAME", "PARSER_VERSION"]
