"""Deterministic database/schema change detector (feature 005, slice 3).

Pure, path-and-metadata-driven detection of schema evidence: migrations, SQL DDL,
ORM models, schema-registry files, and persisted validation schemas. No file
contents or raw diffs are read — only the normalized changed-file metadata and the
diff *handle* from feature 003 (FM-18, NFR-3).

Generated / runtime-reflection patterns attach explicit
:class:`~living_adr.workflow.classifiers.inputs.UncertaintyReason` flags so the
confidence policy lowers certainty rather than the detector silently inflating it
(FM-06, FM-07). Seed/test/comment-only changes are retained as no-ADR outcomes,
never dropped (FR-8).
"""

from __future__ import annotations

from dataclasses import dataclass

from living_adr.core.structural_change import (
    ADRRecommendation,
    ChangeOperation,
    ChangeType,
    EvidenceKind,
    ObservedOperation,
    ReasonCode,
)
from living_adr.workflow.classifiers.confidence import ConfidencePolicy
from living_adr.workflow.classifiers.inputs import (
    ChangedFileEvidence,
    ClassifierInput,
    Detection,
    DetectorOutcome,
    UncertaintyReason,
    make_evidence,
    make_no_adr,
    make_structural_change,
)

PARSER_NAME = "living-adr-schema-evidence"
PARSER_VERSION = "1.0.0"

_SEED_TEST_SEGMENTS = {
    "test",
    "tests",
    "__tests__",
    "seed",
    "seeds",
    "fixture",
    "fixtures",
    "spec",
}


@dataclass(frozen=True)
class _Subtype:
    evidence_kind: EvidenceKind
    reason_code: str
    base_confidence: float


_MIGRATION = _Subtype(
    EvidenceKind.SCHEMA_MIGRATION, ReasonCode.SCHEMA_MIGRATION.value, 0.85
)
_DDL = _Subtype(EvidenceKind.SCHEMA_DDL, ReasonCode.SCHEMA_DDL.value, 0.85)
_REGISTRY = _Subtype(
    EvidenceKind.SCHEMA_REGISTRY, ReasonCode.SCHEMA_REGISTRY.value, 0.82
)
_VALIDATION = _Subtype(
    EvidenceKind.SCHEMA_VALIDATION, ReasonCode.SCHEMA_VALIDATION.value, 0.78
)
_ORM = _Subtype(
    EvidenceKind.SCHEMA_ORM_MODEL, ReasonCode.SCHEMA_ORM_MODEL.value, 0.78
)


def _basename(path: str) -> str:
    return path.rsplit("/", 1)[-1]


def _recognize(path: str) -> _Subtype | None:
    """Recognize a normalized path as a schema-evidence subtype, or ``None``."""

    lower = path.lower()
    name = _basename(lower)
    if any(
        marker in lower
        for marker in ("migration", "/alembic/", "flyway", "liquibase", "changelog")
    ):
        return _MIGRATION
    if lower.endswith(".sql"):
        return _DDL
    if lower.endswith((".prisma", ".avsc")) or "schema-registry" in lower:
        return _REGISTRY
    if lower.endswith(".schema.json") or (
        lower.endswith(".json") and "schema" in name
    ):
        return _VALIDATION
    if lower.endswith(".py") and ("/models/" in lower or name in {
        "models.py",
        "schema.py",
    }):
        return _ORM
    return None


def _uncertainty(path: str) -> tuple[UncertaintyReason, ...]:
    lower = path.lower()
    reasons: list[UncertaintyReason] = []
    if "generated" in lower or "autogenerated" in lower:
        reasons.append(UncertaintyReason.GENERATED_ARTIFACT)
    if "reflect" in lower or "dynamic" in lower:
        reasons.append(UncertaintyReason.RUNTIME_REFLECTION)
    return tuple(reasons)


def _is_seed_or_test(path: str) -> bool:
    lower = path.lower()
    segments = set(lower.split("/"))
    if segments & _SEED_TEST_SEGMENTS:
        return True
    return "seed" in _basename(lower)


def _operation(file: ChangedFileEvidence) -> tuple[ChangeOperation, ObservedOperation]:
    status = file.status.lower()
    if status == "added":
        return ChangeOperation.ADDED, ObservedOperation.ADDED
    if status in ("removed", "deleted"):
        return ChangeOperation.REMOVED, ObservedOperation.REMOVED
    return ChangeOperation.MODIFIED, ObservedOperation.MODIFIED


def _detection(file: ChangedFileEvidence, subtype: _Subtype) -> Detection:
    operation, observed = _operation(file)
    subject = _basename(file.path).rsplit(".", 1)[0]
    seed_or_test = _is_seed_or_test(file.path)
    comment_only = file.additions == 0 and file.deletions == 0

    forced = seed_or_test or comment_only
    no_adr_reason: str | None = None
    base_confidence = subtype.base_confidence
    uncertainty: tuple[UncertaintyReason, ...] = ()
    if forced:
        no_adr_reason = (
            ReasonCode.SEED_OR_TEST_ONLY.value
            if seed_or_test
            else ReasonCode.NO_PERSISTED_SHAPE_CHANGE.value
        )
        base_confidence = 0.30
    else:
        uncertainty = _uncertainty(file.path)

    return Detection(
        change_type=ChangeType.SCHEMA,
        subject=subject,
        source_path=file.path,
        evidence_kind=subtype.evidence_kind,
        reason_code=subtype.reason_code,
        operation=operation,
        observed_operation=observed,
        base_confidence=base_confidence,
        parser=PARSER_NAME,
        parser_version=PARSER_VERSION,
        uncertainty=uncertainty,
        uncertain_reason_code=ReasonCode.SCHEMA_GENERATED_UNCERTAIN.value,
        forced_no_adr=forced,
        no_adr_reason=no_adr_reason,
    )


class SchemaChangeDetector:
    """Pure schema-evidence detector. The first feature 005 trigger class."""

    def __init__(self, policy: ConfidencePolicy | None = None) -> None:
        self.policy = policy or ConfidencePolicy()

    def detect(self, inp: ClassifierInput) -> DetectorOutcome:
        changes = []
        no_adr = []
        evidence = []
        for file in inp.changed_files:
            subtype = _recognize(file.path)
            if subtype is None:
                continue
            detection = _detection(file, subtype)
            assessment = self.policy.assess(detection, inp.repository.key)
            record_evidence = make_evidence(inp, detection, assessment)
            evidence.append(record_evidence)
            if assessment.recommendation is ADRRecommendation.DRAFT:
                changes.append(
                    make_structural_change(
                        inp, detection, record_evidence.id, assessment
                    )
                )
            else:
                no_adr.append(
                    make_no_adr(inp, detection, record_evidence.id, assessment)
                )

        changes.sort(key=lambda c: c.id)
        no_adr.sort(key=lambda o: (o.reason_code, o.id))
        evidence.sort(key=lambda e: e.id)
        return DetectorOutcome(
            changes=tuple(changes),
            no_adr_outcomes=tuple(no_adr),
            evidence=tuple(evidence),
        )


__all__ = ["SchemaChangeDetector", "PARSER_NAME", "PARSER_VERSION"]
